
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Notebook notebook1;
	
	private global::Editors.CellEditor celleditor1;
	
	private global::Gtk.Label label1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = "MainWindow";
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		this.notebook1.TabPos = ((global::Gtk.PositionType)(0));
		this.notebook1.BorderWidth = ((uint)(4));
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.celleditor1 = new global::Editors.CellEditor ();
		this.celleditor1.Events = ((global::Gdk.EventMask)(256));
		this.celleditor1.Name = "celleditor1";
		this.notebook1.Add (this.celleditor1);
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = "Cells";
		this.notebook1.SetTabLabel (this.celleditor1, this.label1);
		this.label1.ShowAll ();
		this.Add (this.notebook1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 596;
		this.DefaultHeight = 417;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
