
// This file has been generated by the GUI designer. Do not modify.
namespace Editors
{
	public partial class Vector3Editor
	{
		private global::Gtk.HBox hbox11;
		
		private global::Gtk.Entry entry5;
		
		private global::Gtk.Entry entry6;
		
		private global::Gtk.Entry entry7;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Editors.Vector3Editor
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Editors.Vector3Editor";
			// Container child Editors.Vector3Editor.Gtk.Container+ContainerChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.entry5 = new global::Gtk.Entry ();
			this.entry5.WidthRequest = 0;
			this.entry5.HeightRequest = 0;
			this.entry5.CanFocus = true;
			this.entry5.Name = "entry5";
			this.entry5.Text = global::Mono.Unix.Catalog.GetString ("1.0");
			this.entry5.IsEditable = true;
			this.entry5.WidthChars = 5;
			this.entry5.InvisibleChar = '●';
			this.hbox11.Add (this.entry5);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.entry5]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.entry6 = new global::Gtk.Entry ();
			this.entry6.CanFocus = true;
			this.entry6.Name = "entry6";
			this.entry6.Text = global::Mono.Unix.Catalog.GetString ("1.0");
			this.entry6.IsEditable = true;
			this.entry6.WidthChars = 5;
			this.entry6.InvisibleChar = '●';
			this.hbox11.Add (this.entry6);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.entry6]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.entry7 = new global::Gtk.Entry ();
			this.entry7.CanFocus = true;
			this.entry7.Name = "entry7";
			this.entry7.Text = global::Mono.Unix.Catalog.GetString ("1.0");
			this.entry7.IsEditable = true;
			this.entry7.WidthChars = 5;
			this.entry7.InvisibleChar = '●';
			this.hbox11.Add (this.entry7);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.entry7]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.Add (this.hbox11);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
