
// This file has been generated by the GUI designer. Do not modify.
namespace Editors
{
	public partial class CellEditor
	{
		private global::Gtk.HPaned hpaned1;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow4;
		
		private global::Gtk.NodeView nvCells;
		
		private global::Gtk.HButtonBox hbuttonbox6;
		
		private global::Gtk.Button btnNewCell;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.ScrolledWindow scrolledwindow1;
		
		private global::Gtk.VBox vbContent;
		
		private global::Gtk.Label lblName;
		
		private global::Gtk.HSeparator hseparator2;
		
		private global::Gtk.Expander expander2;
		
		private global::Gtk.Table table2;
		
		private global::Gtk.CheckButton checkbutton3;
		
		private global::Gtk.CheckButton checkbutton4;
		
		private global::Gtk.CheckButton checkbutton5;
		
		private global::Gtk.CheckButton checkbutton6;
		
		private global::Gtk.CheckButton checkbutton8;
		
		private global::Gtk.CheckButton checkbutton9;
		
		private global::Gtk.Label GtkLabel7;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.Expander expander1;
		
		private global::Gtk.Table tblTexture;
		
		private global::Gtk.CheckButton checkbutton12;
		
		private global::Gtk.CheckButton checkbutton13;
		
		private global::Gtk.CheckButton checkbutton2;
		
		private global::Gtk.Label label10;
		
		private global::Editors.SideFlags sideflags4;
		
		private global::Editors.SideFlags sideflags6;
		
		private global::Editors.TextureSelection textureselection1;
		
		private global::Editors.TextureSelection textureselection2;
		
		private global::Editors.TextureSelection textureselection3;
		
		private global::Editors.TextureSelection textureselection4;
		
		private global::Editors.Vector3Editor vector3editor1;
		
		private global::Gtk.Label GtkLabel26;
		
		private global::Gtk.HSeparator hseparator3;
		
		private global::Gtk.Expander expander3;
		
		private global::Gtk.VBox vbox7;
		
		private global::Gtk.Table table3;
		
		private global::Gtk.CheckButton checkbutton1;
		
		private global::Gtk.CheckButton checkbutton7;
		
		private global::Gtk.ComboBox combobox1;
		
		private global::Gtk.Entry entry1;
		
		private global::Gtk.Entry entry14;
		
		private global::Gtk.Entry entry15;
		
		private global::Gtk.Entry entry2;
		
		private global::Gtk.Entry entry3;
		
		private global::Gtk.Entry entry4;
		
		private global::Gtk.Label label15;
		
		private global::Gtk.Label label16;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Label label9;
		
		private global::Editors.SideFlags sideflags2;
		
		private global::Editors.SideFlags sideflags3;
		
		private global::Editors.SideFlags sideflags5;
		
		private global::Gtk.Label GtkLabel47;
		
		private global::Gtk.HSeparator hseparator4;
		
		private global::Gtk.Expander expander4;
		
		private global::Gtk.Table table4;
		
		private global::Gtk.ComboBox combobox2;
		
		private global::Gtk.ComboBox combobox3;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Label GtkLabel49;
		
		private global::Gtk.HSeparator hseparator5;
		
		private global::Gtk.Expander expander5;
		
		private global::Gtk.Table table5;
		
		private global::Gtk.Entry entry11;
		
		private global::Gtk.Entry entry12;
		
		private global::Gtk.Entry entry13;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.Label label14;
		
		private global::Editors.Vector3Editor vector3editor2;
		
		private global::Gtk.Label GtkLabel50;
		
		private global::Gtk.HButtonBox hbuttonbox5;
		
		private global::Gtk.Button button2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Editors.CellEditor
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Editors.CellEditor";
			// Container child Editors.CellEditor.Gtk.Container+ContainerChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 177;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
			this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
			this.nvCells = new global::Gtk.NodeView ();
			this.nvCells.CanFocus = true;
			this.nvCells.Name = "nvCells";
			this.GtkScrolledWindow4.Add (this.nvCells);
			this.vbox2.Add (this.GtkScrolledWindow4);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow4]));
			w2.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbuttonbox6 = new global::Gtk.HButtonBox ();
			this.hbuttonbox6.Name = "hbuttonbox6";
			this.hbuttonbox6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox6.Gtk.ButtonBox+ButtonBoxChild
			this.btnNewCell = new global::Gtk.Button ();
			this.btnNewCell.CanFocus = true;
			this.btnNewCell.Name = "btnNewCell";
			this.btnNewCell.UseStock = true;
			this.btnNewCell.UseUnderline = true;
			this.btnNewCell.Label = "gtk-new";
			this.hbuttonbox6.Add (this.btnNewCell);
			global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox6 [this.btnNewCell]));
			w3.Expand = false;
			w3.Fill = false;
			this.vbox2.Add (this.hbuttonbox6);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbuttonbox6]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.hpaned1.Add (this.vbox2);
			global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.vbox2]));
			w5.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w6 = new global::Gtk.Viewport ();
			w6.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vbContent = new global::Gtk.VBox ();
			this.vbContent.Name = "vbContent";
			this.vbContent.Spacing = 6;
			this.vbContent.BorderWidth = ((uint)(4));
			// Container child vbContent.Gtk.Box+BoxChild
			this.lblName = new global::Gtk.Label ();
			this.lblName.Name = "lblName";
			this.lblName.Xalign = 0F;
			this.lblName.LabelProp = global::Mono.Unix.Catalog.GetString ("name");
			this.vbContent.Add (this.lblName);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbContent [this.lblName]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbContent.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbContent.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbContent [this.hseparator2]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbContent.Gtk.Box+BoxChild
			this.expander2 = new global::Gtk.Expander (null);
			this.expander2.CanFocus = true;
			this.expander2.Name = "expander2";
			this.expander2.Expanded = true;
			// Container child expander2.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table (((uint)(2)), ((uint)(3)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.checkbutton3 = new global::Gtk.CheckButton ();
			this.checkbutton3.CanFocus = true;
			this.checkbutton3.Name = "checkbutton3";
			this.checkbutton3.Label = global::Mono.Unix.Catalog.GetString ("Solid");
			this.checkbutton3.DrawIndicator = true;
			this.checkbutton3.UseUnderline = true;
			this.table2.Add (this.checkbutton3);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2 [this.checkbutton3]));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.checkbutton4 = new global::Gtk.CheckButton ();
			this.checkbutton4.CanFocus = true;
			this.checkbutton4.Name = "checkbutton4";
			this.checkbutton4.Label = global::Mono.Unix.Catalog.GetString ("Transparent");
			this.checkbutton4.DrawIndicator = true;
			this.checkbutton4.UseUnderline = true;
			this.table2.Add (this.checkbutton4);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.checkbutton4]));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.checkbutton5 = new global::Gtk.CheckButton ();
			this.checkbutton5.CanFocus = true;
			this.checkbutton5.Name = "checkbutton5";
			this.checkbutton5.Label = global::Mono.Unix.Catalog.GetString ("Dynamic");
			this.checkbutton5.DrawIndicator = true;
			this.checkbutton5.UseUnderline = true;
			this.table2.Add (this.checkbutton5);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.checkbutton5]));
			w11.LeftAttach = ((uint)(2));
			w11.RightAttach = ((uint)(3));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.checkbutton6 = new global::Gtk.CheckButton ();
			this.checkbutton6.CanFocus = true;
			this.checkbutton6.Name = "checkbutton6";
			this.checkbutton6.Label = global::Mono.Unix.Catalog.GetString ("Wave");
			this.checkbutton6.DrawIndicator = true;
			this.checkbutton6.UseUnderline = true;
			this.table2.Add (this.checkbutton6);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.checkbutton6]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.checkbutton8 = new global::Gtk.CheckButton ();
			this.checkbutton8.CanFocus = true;
			this.checkbutton8.Name = "checkbutton8";
			this.checkbutton8.Label = global::Mono.Unix.Catalog.GetString ("Liquid");
			this.checkbutton8.DrawIndicator = true;
			this.checkbutton8.UseUnderline = true;
			this.table2.Add (this.checkbutton8);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2 [this.checkbutton8]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.checkbutton9 = new global::Gtk.CheckButton ();
			this.checkbutton9.CanFocus = true;
			this.checkbutton9.Name = "checkbutton9";
			this.checkbutton9.Label = global::Mono.Unix.Catalog.GetString ("Ladder");
			this.checkbutton9.DrawIndicator = true;
			this.checkbutton9.UseUnderline = true;
			this.table2.Add (this.checkbutton9);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2 [this.checkbutton9]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.LeftAttach = ((uint)(2));
			w14.RightAttach = ((uint)(3));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			this.expander2.Add (this.table2);
			this.GtkLabel7 = new global::Gtk.Label ();
			this.GtkLabel7.Name = "GtkLabel7";
			this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("Flags");
			this.GtkLabel7.UseUnderline = true;
			this.expander2.LabelWidget = this.GtkLabel7;
			this.vbContent.Add (this.expander2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbContent [this.expander2]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbContent.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbContent.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbContent [this.hseparator1]));
			w17.Position = 3;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbContent.Gtk.Box+BoxChild
			this.expander1 = new global::Gtk.Expander (null);
			this.expander1.CanFocus = true;
			this.expander1.Name = "expander1";
			// Container child expander1.Gtk.Container+ContainerChild
			this.tblTexture = new global::Gtk.Table (((uint)(8)), ((uint)(2)), false);
			this.tblTexture.Name = "tblTexture";
			this.tblTexture.RowSpacing = ((uint)(6));
			this.tblTexture.ColumnSpacing = ((uint)(6));
			// Container child tblTexture.Gtk.Table+TableChild
			this.checkbutton12 = new global::Gtk.CheckButton ();
			this.checkbutton12.CanFocus = true;
			this.checkbutton12.Name = "checkbutton12";
			this.checkbutton12.Label = global::Mono.Unix.Catalog.GetString ("UV Turbulence");
			this.checkbutton12.DrawIndicator = true;
			this.checkbutton12.UseUnderline = true;
			this.tblTexture.Add (this.checkbutton12);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.tblTexture [this.checkbutton12]));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTexture.Gtk.Table+TableChild
			this.checkbutton13 = new global::Gtk.CheckButton ();
			this.checkbutton13.CanFocus = true;
			this.checkbutton13.Name = "checkbutton13";
			this.checkbutton13.Label = global::Mono.Unix.Catalog.GetString ("Render backfaces");
			this.checkbutton13.DrawIndicator = true;
			this.checkbutton13.UseUnderline = true;
			this.tblTexture.Add (this.checkbutton13);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.tblTexture [this.checkbutton13]));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTexture.Gtk.Table+TableChild
			this.checkbutton2 = new global::Gtk.CheckButton ();
			this.checkbutton2.CanFocus = true;
			this.checkbutton2.Name = "checkbutton2";
			this.checkbutton2.Label = global::Mono.Unix.Catalog.GetString ("Multi faced");
			this.checkbutton2.DrawIndicator = true;
			this.checkbutton2.UseUnderline = true;
			this.tblTexture.Add (this.checkbutton2);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.tblTexture [this.checkbutton2]));
			w20.TopAttach = ((uint)(1));
			w20.BottomAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTexture.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.Xalign = 0F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Scale XYZ:");
			this.tblTexture.Add (this.label10);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.tblTexture [this.label10]));
			w21.TopAttach = ((uint)(2));
			w21.BottomAttach = ((uint)(3));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTexture.Gtk.Table+TableChild
			this.sideflags4 = new global::Editors.SideFlags ();
			this.sideflags4.Events = ((global::Gdk.EventMask)(256));
			this.sideflags4.Name = "sideflags4";
			this.tblTexture.Add (this.sideflags4);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.tblTexture [this.sideflags4]));
			w22.TopAttach = ((uint)(3));
			w22.BottomAttach = ((uint)(4));
			w22.LeftAttach = ((uint)(1));
			w22.RightAttach = ((uint)(2));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTexture.Gtk.Table+TableChild
			this.sideflags6 = new global::Editors.SideFlags ();
			this.sideflags6.Events = ((global::Gdk.EventMask)(256));
			this.sideflags6.Name = "sideflags6";
			this.tblTexture.Add (this.sideflags6);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.tblTexture [this.sideflags6]));
			w23.TopAttach = ((uint)(3));
			w23.BottomAttach = ((uint)(4));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTexture.Gtk.Table+TableChild
			this.textureselection1 = new global::Editors.TextureSelection ();
			this.textureselection1.Events = ((global::Gdk.EventMask)(256));
			this.textureselection1.Name = "textureselection1";
			this.textureselection1.Title = "Inactive";
			this.tblTexture.Add (this.textureselection1);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.tblTexture [this.textureselection1]));
			w24.TopAttach = ((uint)(4));
			w24.BottomAttach = ((uint)(5));
			// Container child tblTexture.Gtk.Table+TableChild
			this.textureselection2 = new global::Editors.TextureSelection ();
			this.textureselection2.Events = ((global::Gdk.EventMask)(256));
			this.textureselection2.Name = "textureselection2";
			this.textureselection2.Title = "Inactive Emissive";
			this.tblTexture.Add (this.textureselection2);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.tblTexture [this.textureselection2]));
			w25.TopAttach = ((uint)(4));
			w25.BottomAttach = ((uint)(5));
			w25.LeftAttach = ((uint)(1));
			w25.RightAttach = ((uint)(2));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTexture.Gtk.Table+TableChild
			this.textureselection3 = new global::Editors.TextureSelection ();
			this.textureselection3.Events = ((global::Gdk.EventMask)(256));
			this.textureselection3.Name = "textureselection3";
			this.textureselection3.Title = "Active";
			this.tblTexture.Add (this.textureselection3);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.tblTexture [this.textureselection3]));
			w26.TopAttach = ((uint)(5));
			w26.BottomAttach = ((uint)(6));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblTexture.Gtk.Table+TableChild
			this.textureselection4 = new global::Editors.TextureSelection ();
			this.textureselection4.Events = ((global::Gdk.EventMask)(256));
			this.textureselection4.Name = "textureselection4";
			this.textureselection4.Title = "Active Emissive";
			this.tblTexture.Add (this.textureselection4);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.tblTexture [this.textureselection4]));
			w27.TopAttach = ((uint)(5));
			w27.BottomAttach = ((uint)(6));
			w27.LeftAttach = ((uint)(1));
			w27.RightAttach = ((uint)(2));
			// Container child tblTexture.Gtk.Table+TableChild
			this.vector3editor1 = new global::Editors.Vector3Editor ();
			this.vector3editor1.Events = ((global::Gdk.EventMask)(256));
			this.vector3editor1.Name = "vector3editor1";
			this.tblTexture.Add (this.vector3editor1);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.tblTexture [this.vector3editor1]));
			w28.TopAttach = ((uint)(2));
			w28.BottomAttach = ((uint)(3));
			w28.LeftAttach = ((uint)(1));
			w28.RightAttach = ((uint)(2));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			this.expander1.Add (this.tblTexture);
			this.GtkLabel26 = new global::Gtk.Label ();
			this.GtkLabel26.Name = "GtkLabel26";
			this.GtkLabel26.LabelProp = global::Mono.Unix.Catalog.GetString ("Rendering");
			this.GtkLabel26.UseUnderline = true;
			this.expander1.LabelWidget = this.GtkLabel26;
			this.vbContent.Add (this.expander1);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbContent [this.expander1]));
			w30.Position = 4;
			w30.Expand = false;
			// Container child vbContent.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			this.vbContent.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbContent [this.hseparator3]));
			w31.Position = 5;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbContent.Gtk.Box+BoxChild
			this.expander3 = new global::Gtk.Expander (null);
			this.expander3.CanFocus = true;
			this.expander3.Name = "expander3";
			// Container child expander3.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table (((uint)(10)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.checkbutton1 = new global::Gtk.CheckButton ();
			this.checkbutton1.CanFocus = true;
			this.checkbutton1.Name = "checkbutton1";
			this.checkbutton1.Label = global::Mono.Unix.Catalog.GetString ("Usable with \"E\", cascading to sides:");
			this.checkbutton1.DrawIndicator = true;
			this.checkbutton1.UseUnderline = true;
			this.table3.Add (this.checkbutton1);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table3 [this.checkbutton1]));
			w32.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.checkbutton7 = new global::Gtk.CheckButton ();
			this.checkbutton7.CanFocus = true;
			this.checkbutton7.Name = "checkbutton7";
			this.checkbutton7.Label = global::Mono.Unix.Catalog.GetString ("Replace on use with:");
			this.checkbutton7.DrawIndicator = true;
			this.checkbutton7.UseUnderline = true;
			this.table3.Add (this.checkbutton7);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table3 [this.checkbutton7]));
			w33.TopAttach = ((uint)(1));
			w33.BottomAttach = ((uint)(2));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.combobox1 = global::Gtk.ComboBox.NewText ();
			this.combobox1.Name = "combobox1";
			this.table3.Add (this.combobox1);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table3 [this.combobox1]));
			w34.TopAttach = ((uint)(1));
			w34.BottomAttach = ((uint)(2));
			w34.LeftAttach = ((uint)(1));
			w34.RightAttach = ((uint)(2));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '●';
			this.table3.Add (this.entry1);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table3 [this.entry1]));
			w35.TopAttach = ((uint)(2));
			w35.BottomAttach = ((uint)(3));
			w35.LeftAttach = ((uint)(1));
			w35.RightAttach = ((uint)(2));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry14 = new global::Gtk.Entry ();
			this.entry14.CanFocus = true;
			this.entry14.Name = "entry14";
			this.entry14.IsEditable = true;
			this.entry14.InvisibleChar = '●';
			this.table3.Add (this.entry14);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table3 [this.entry14]));
			w36.TopAttach = ((uint)(8));
			w36.BottomAttach = ((uint)(9));
			w36.LeftAttach = ((uint)(1));
			w36.RightAttach = ((uint)(2));
			w36.XOptions = ((global::Gtk.AttachOptions)(4));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry15 = new global::Gtk.Entry ();
			this.entry15.CanFocus = true;
			this.entry15.Name = "entry15";
			this.entry15.IsEditable = true;
			this.entry15.InvisibleChar = '●';
			this.table3.Add (this.entry15);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table3 [this.entry15]));
			w37.TopAttach = ((uint)(9));
			w37.BottomAttach = ((uint)(10));
			w37.LeftAttach = ((uint)(1));
			w37.RightAttach = ((uint)(2));
			w37.XOptions = ((global::Gtk.AttachOptions)(4));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry2 = new global::Gtk.Entry ();
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '●';
			this.table3.Add (this.entry2);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table3 [this.entry2]));
			w38.TopAttach = ((uint)(6));
			w38.BottomAttach = ((uint)(7));
			w38.LeftAttach = ((uint)(1));
			w38.RightAttach = ((uint)(2));
			w38.XOptions = ((global::Gtk.AttachOptions)(4));
			w38.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry3 = new global::Gtk.Entry ();
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '●';
			this.table3.Add (this.entry3);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table3 [this.entry3]));
			w39.TopAttach = ((uint)(7));
			w39.BottomAttach = ((uint)(8));
			w39.LeftAttach = ((uint)(1));
			w39.RightAttach = ((uint)(2));
			w39.XOptions = ((global::Gtk.AttachOptions)(4));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.entry4 = new global::Gtk.Entry ();
			this.entry4.CanFocus = true;
			this.entry4.Name = "entry4";
			this.entry4.IsEditable = true;
			this.entry4.InvisibleChar = '●';
			this.table3.Add (this.entry4);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table3 [this.entry4]));
			w40.TopAttach = ((uint)(3));
			w40.BottomAttach = ((uint)(4));
			w40.LeftAttach = ((uint)(1));
			w40.RightAttach = ((uint)(2));
			w40.XOptions = ((global::Gtk.AttachOptions)(4));
			w40.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.Xalign = 0F;
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Speed factor:");
			this.table3.Add (this.label15);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table3 [this.label15]));
			w41.TopAttach = ((uint)(8));
			w41.BottomAttach = ((uint)(9));
			w41.XOptions = ((global::Gtk.AttachOptions)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.Xalign = 0F;
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Friction:");
			this.table3.Add (this.label16);
			global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table3 [this.label16]));
			w42.TopAttach = ((uint)(9));
			w42.BottomAttach = ((uint)(10));
			w42.XOptions = ((global::Gtk.AttachOptions)(4));
			w42.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Clip into sides:");
			this.table3.Add (this.label2);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table3 [this.label2]));
			w43.TopAttach = ((uint)(4));
			w43.BottomAttach = ((uint)(5));
			w43.XOptions = ((global::Gtk.AttachOptions)(4));
			w43.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Clip out of sides:");
			this.table3.Add (this.label3);
			global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table3 [this.label3]));
			w44.TopAttach = ((uint)(5));
			w44.BottomAttach = ((uint)(6));
			w44.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Delay between uses:");
			this.table3.Add (this.label4);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table3 [this.label4]));
			w45.TopAttach = ((uint)(2));
			w45.BottomAttach = ((uint)(3));
			w45.XOptions = ((global::Gtk.AttachOptions)(4));
			w45.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Locked chance:");
			this.table3.Add (this.label5);
			global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table3 [this.label5]));
			w46.TopAttach = ((uint)(6));
			w46.BottomAttach = ((uint)(7));
			w46.XOptions = ((global::Gtk.AttachOptions)(4));
			w46.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Strength");
			this.table3.Add (this.label6);
			global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.table3 [this.label6]));
			w47.TopAttach = ((uint)(7));
			w47.BottomAttach = ((uint)(8));
			w47.XOptions = ((global::Gtk.AttachOptions)(4));
			w47.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.Xalign = 0F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Use chance:");
			this.table3.Add (this.label9);
			global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table3 [this.label9]));
			w48.TopAttach = ((uint)(3));
			w48.BottomAttach = ((uint)(4));
			w48.XOptions = ((global::Gtk.AttachOptions)(4));
			w48.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.sideflags2 = new global::Editors.SideFlags ();
			this.sideflags2.Events = ((global::Gdk.EventMask)(256));
			this.sideflags2.Name = "sideflags2";
			this.table3.Add (this.sideflags2);
			global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.table3 [this.sideflags2]));
			w49.TopAttach = ((uint)(4));
			w49.BottomAttach = ((uint)(5));
			w49.LeftAttach = ((uint)(1));
			w49.RightAttach = ((uint)(2));
			w49.XOptions = ((global::Gtk.AttachOptions)(4));
			w49.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.sideflags3 = new global::Editors.SideFlags ();
			this.sideflags3.Events = ((global::Gdk.EventMask)(256));
			this.sideflags3.Name = "sideflags3";
			this.table3.Add (this.sideflags3);
			global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.table3 [this.sideflags3]));
			w50.TopAttach = ((uint)(5));
			w50.BottomAttach = ((uint)(6));
			w50.LeftAttach = ((uint)(1));
			w50.RightAttach = ((uint)(2));
			w50.XOptions = ((global::Gtk.AttachOptions)(4));
			w50.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.sideflags5 = new global::Editors.SideFlags ();
			this.sideflags5.Events = ((global::Gdk.EventMask)(256));
			this.sideflags5.Name = "sideflags5";
			this.table3.Add (this.sideflags5);
			global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.table3 [this.sideflags5]));
			w51.LeftAttach = ((uint)(1));
			w51.RightAttach = ((uint)(2));
			w51.XOptions = ((global::Gtk.AttachOptions)(4));
			w51.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox7.Add (this.table3);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.table3]));
			w52.Position = 0;
			w52.Expand = false;
			w52.Fill = false;
			this.expander3.Add (this.vbox7);
			this.GtkLabel47 = new global::Gtk.Label ();
			this.GtkLabel47.Name = "GtkLabel47";
			this.GtkLabel47.LabelProp = global::Mono.Unix.Catalog.GetString ("Gameplay");
			this.GtkLabel47.UseUnderline = true;
			this.expander3.LabelWidget = this.GtkLabel47;
			this.vbContent.Add (this.expander3);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vbContent [this.expander3]));
			w54.Position = 6;
			w54.Expand = false;
			// Container child vbContent.Gtk.Box+BoxChild
			this.hseparator4 = new global::Gtk.HSeparator ();
			this.hseparator4.Name = "hseparator4";
			this.vbContent.Add (this.hseparator4);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbContent [this.hseparator4]));
			w55.Position = 7;
			w55.Expand = false;
			w55.Fill = false;
			// Container child vbContent.Gtk.Box+BoxChild
			this.expander4 = new global::Gtk.Expander (null);
			this.expander4.CanFocus = true;
			this.expander4.Name = "expander4";
			// Container child expander4.Gtk.Container+ContainerChild
			this.table4 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.combobox2 = global::Gtk.ComboBox.NewText ();
			this.combobox2.Name = "combobox2";
			this.table4.Add (this.combobox2);
			global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.table4 [this.combobox2]));
			w56.LeftAttach = ((uint)(1));
			w56.RightAttach = ((uint)(2));
			w56.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.combobox3 = global::Gtk.ComboBox.NewText ();
			this.combobox3.Name = "combobox3";
			this.table4.Add (this.combobox3);
			global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.table4 [this.combobox3]));
			w57.TopAttach = ((uint)(1));
			w57.BottomAttach = ((uint)(2));
			w57.LeftAttach = ((uint)(1));
			w57.RightAttach = ((uint)(2));
			w57.XOptions = ((global::Gtk.AttachOptions)(4));
			w57.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Use:");
			this.table4.Add (this.label7);
			global::Gtk.Table.TableChild w58 = ((global::Gtk.Table.TableChild)(this.table4 [this.label7]));
			w58.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xalign = 0F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Use when locked:");
			this.table4.Add (this.label8);
			global::Gtk.Table.TableChild w59 = ((global::Gtk.Table.TableChild)(this.table4 [this.label8]));
			w59.TopAttach = ((uint)(1));
			w59.BottomAttach = ((uint)(2));
			w59.YOptions = ((global::Gtk.AttachOptions)(4));
			this.expander4.Add (this.table4);
			this.GtkLabel49 = new global::Gtk.Label ();
			this.GtkLabel49.Name = "GtkLabel49";
			this.GtkLabel49.LabelProp = global::Mono.Unix.Catalog.GetString ("Audio");
			this.GtkLabel49.UseUnderline = true;
			this.expander4.LabelWidget = this.GtkLabel49;
			this.vbContent.Add (this.expander4);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.vbContent [this.expander4]));
			w61.Position = 8;
			w61.Expand = false;
			// Container child vbContent.Gtk.Box+BoxChild
			this.hseparator5 = new global::Gtk.HSeparator ();
			this.hseparator5.Name = "hseparator5";
			this.vbContent.Add (this.hseparator5);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbContent [this.hseparator5]));
			w62.Position = 9;
			w62.Expand = false;
			w62.Fill = false;
			// Container child vbContent.Gtk.Box+BoxChild
			this.expander5 = new global::Gtk.Expander (null);
			this.expander5.CanFocus = true;
			this.expander5.Name = "expander5";
			// Container child expander5.Gtk.Container+ContainerChild
			this.table5 = new global::Gtk.Table (((uint)(4)), ((uint)(2)), false);
			this.table5.Name = "table5";
			this.table5.RowSpacing = ((uint)(6));
			this.table5.ColumnSpacing = ((uint)(6));
			// Container child table5.Gtk.Table+TableChild
			this.entry11 = new global::Gtk.Entry ();
			this.entry11.CanFocus = true;
			this.entry11.Name = "entry11";
			this.entry11.IsEditable = true;
			this.entry11.InvisibleChar = '●';
			this.table5.Add (this.entry11);
			global::Gtk.Table.TableChild w63 = ((global::Gtk.Table.TableChild)(this.table5 [this.entry11]));
			w63.TopAttach = ((uint)(1));
			w63.BottomAttach = ((uint)(2));
			w63.LeftAttach = ((uint)(1));
			w63.RightAttach = ((uint)(2));
			w63.XOptions = ((global::Gtk.AttachOptions)(4));
			w63.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.entry12 = new global::Gtk.Entry ();
			this.entry12.CanFocus = true;
			this.entry12.Name = "entry12";
			this.entry12.IsEditable = true;
			this.entry12.InvisibleChar = '●';
			this.table5.Add (this.entry12);
			global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.table5 [this.entry12]));
			w64.TopAttach = ((uint)(2));
			w64.BottomAttach = ((uint)(3));
			w64.LeftAttach = ((uint)(1));
			w64.RightAttach = ((uint)(2));
			w64.XOptions = ((global::Gtk.AttachOptions)(4));
			w64.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.entry13 = new global::Gtk.Entry ();
			this.entry13.CanFocus = true;
			this.entry13.Name = "entry13";
			this.entry13.IsEditable = true;
			this.entry13.InvisibleChar = '●';
			this.table5.Add (this.entry13);
			global::Gtk.Table.TableChild w65 = ((global::Gtk.Table.TableChild)(this.table5 [this.entry13]));
			w65.TopAttach = ((uint)(3));
			w65.BottomAttach = ((uint)(4));
			w65.LeftAttach = ((uint)(1));
			w65.RightAttach = ((uint)(2));
			w65.XOptions = ((global::Gtk.AttachOptions)(4));
			w65.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 0F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Light:");
			this.table5.Add (this.label11);
			global::Gtk.Table.TableChild w66 = ((global::Gtk.Table.TableChild)(this.table5 [this.label11]));
			w66.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 0F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Scale:");
			this.table5.Add (this.label12);
			global::Gtk.Table.TableChild w67 = ((global::Gtk.Table.TableChild)(this.table5 [this.label12]));
			w67.TopAttach = ((uint)(1));
			w67.BottomAttach = ((uint)(2));
			w67.XOptions = ((global::Gtk.AttachOptions)(4));
			w67.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.Xalign = 0F;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Spreading factor:");
			this.table5.Add (this.label13);
			global::Gtk.Table.TableChild w68 = ((global::Gtk.Table.TableChild)(this.table5 [this.label13]));
			w68.TopAttach = ((uint)(2));
			w68.BottomAttach = ((uint)(3));
			w68.XOptions = ((global::Gtk.AttachOptions)(4));
			w68.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.Xalign = 0F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Spreading fade:");
			this.table5.Add (this.label14);
			global::Gtk.Table.TableChild w69 = ((global::Gtk.Table.TableChild)(this.table5 [this.label14]));
			w69.TopAttach = ((uint)(3));
			w69.BottomAttach = ((uint)(4));
			w69.XOptions = ((global::Gtk.AttachOptions)(4));
			w69.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.vector3editor2 = new global::Editors.Vector3Editor ();
			this.vector3editor2.Events = ((global::Gdk.EventMask)(256));
			this.vector3editor2.Name = "vector3editor2";
			this.table5.Add (this.vector3editor2);
			global::Gtk.Table.TableChild w70 = ((global::Gtk.Table.TableChild)(this.table5 [this.vector3editor2]));
			w70.LeftAttach = ((uint)(1));
			w70.RightAttach = ((uint)(2));
			w70.YOptions = ((global::Gtk.AttachOptions)(4));
			this.expander5.Add (this.table5);
			this.GtkLabel50 = new global::Gtk.Label ();
			this.GtkLabel50.Name = "GtkLabel50";
			this.GtkLabel50.LabelProp = global::Mono.Unix.Catalog.GetString ("Light");
			this.GtkLabel50.UseUnderline = true;
			this.expander5.LabelWidget = this.GtkLabel50;
			this.vbContent.Add (this.expander5);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.vbContent [this.expander5]));
			w72.Position = 10;
			w72.Expand = false;
			w72.Fill = false;
			w6.Add (this.vbContent);
			this.scrolledwindow1.Add (w6);
			this.vbox1.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.scrolledwindow1]));
			w75.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbuttonbox5 = new global::Gtk.HButtonBox ();
			this.hbuttonbox5.Name = "hbuttonbox5";
			this.hbuttonbox5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseStock = true;
			this.button2.UseUnderline = true;
			this.button2.Label = "gtk-save";
			this.hbuttonbox5.Add (this.button2);
			global::Gtk.ButtonBox.ButtonBoxChild w76 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5 [this.button2]));
			w76.Expand = false;
			w76.Fill = false;
			this.vbox1.Add (this.hbuttonbox5);
			global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbuttonbox5]));
			w77.Position = 1;
			w77.Expand = false;
			w77.Fill = false;
			this.hpaned1.Add (this.vbox1);
			this.Add (this.hpaned1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.btnNewCell.Clicked += new global::System.EventHandler (this.OnBtnNewCellClicked);
		}
	}
}
